### ISSUE TITLE
有下底线的ID似乎搜寻不到

### ISSUE THREAD

**Issue by jason21415** [insorker/Bilibili-Comment-Search#1]
像是"leo_soul"
0 | 0 搜索完成

**Comment by insorker** [comment]
你好，我尝试了复现你的说法，但是没有成功。比如这个[视频](https://www.bilibili.com/video/BV1DL4y1E7ai/)下搜索 “_WHOAMI”，结果成功搜索到了

![PixPin_2024-11-19_22-02-51](https://github.com/user-attachments/assets/11a8223e-daa5-4781-b505-a6406fc3e0a8)

我不太清楚你具体搜索的过程，你可以确认一下安装的插件是否是最新的 0.3.0 版本，并且复制粘贴搜索内容再尝试搜索，如果没搜到可以再和我反馈一下（比如随便找个视频，搜索含有下划线的内容不成功，然后把链接和搜索内容 comment 一下）。

**Comment by jason21415** [comment]
_WHOAMI我测试正常 版本3.0

[视频](https://www.bilibili.com/video/BV1kiUVYiEtr/?share_source=copy_web&vd_source=6b3e22a9b87a48d0df0b6373819579eb)我测试了一下应该是那些评论被客服处理过
不明原因看的到但查不到 没有互相拉黑 已清除cookie 也重登过
其他视频底下相同人物发言就可以查到
![TEST-1](https://github.com/user-attachments/assets/bc816b24-9817-47bc-b155-a80eb2b7e36f)
![TEST-2](https://github.com/user-attachments/assets/9174dbb8-27f6-4404-919f-c14b6927bf40)
找其他人都是正常的
![TEST-3](https://github.com/user-attachments/assets/36c97335-11d7-42b7-9250-e690e3f0d33d)

**Comment by insorker** [comment]
确实是 bug，已经在 0.3.2 版本修复了。

**Comment by jason21415** [comment]
> 确实是 bug，已经在 0.3.2 版本修复了。

新版本测试正常了
